name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node.js v22
        uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '22.x'  # Install Node.js v22

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install --legacy-peer-deps 
          npm run build
          touch build/.nojekyll
          cp build/404.html build/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          branch: gh-pages
